name: Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build documentation
      run: npm run build
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 64.225.64.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create directory if it doesn't exist
          mkdir -p /root/hx_docs
          
          # Clean old files
          rm -rf /root/hx_docs/*
    
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 64.225.64.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "out/*"
        target: "/root/hx_docs"
        strip_components: 1
    
    - name: Set permissions
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 64.225.64.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Set proper permissions
          chmod -R 755 /root/hx_docs
          
          # If using nginx, you might need to reload it
          # nginx -s reload
          
          echo "Deployment complete! Documentation available at your server."